//Algoritmo "ESTRUTURAS DE REPETICAO 1"
// Aula 9
// nome:  conte ate 10
//Var
 //  contador,valor: Inteiro

//Inicio
  // contador <-0  ,
  // escreva("Quer contar até qual numero? ")
 //  leia (valor)
 //  enquanto  (contador <=valor) faca
 //     escreval(contador)
 //     contador<-contador +1
  // fimenquanto
//   escreval ("Terminei de contar")

//Fimalgoritmo

//Exercicio 2

algoritmo"ESTRUTURAS DE REPETICAO 1"
//aula 9
//nome:somador numerico

inicio